# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lewis_e/rendu/cpp/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lewis_e/rendu/cpp/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lewis_e/rendu/cpp/cpp_indie_studio/CMakeFiles /home/lewis_e/rendu/cpp/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lewis_e/rendu/cpp/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_indie_studio

# Build rule for target.
cpp_indie_studio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_indie_studio
.PHONY : cpp_indie_studio

# fast build rule for target.
cpp_indie_studio/fast:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/build
.PHONY : cpp_indie_studio/fast

src/World.o: src/World.cpp.o
.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i
.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s
.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/core/Core.o: src/core/Core.cpp.o
.PHONY : src/core/Core.o

# target to build an object file
src/core/Core.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Core.cpp.o
.PHONY : src/core/Core.cpp.o

src/core/Core.i: src/core/Core.cpp.i
.PHONY : src/core/Core.i

# target to preprocess a source file
src/core/Core.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Core.cpp.i
.PHONY : src/core/Core.cpp.i

src/core/Core.s: src/core/Core.cpp.s
.PHONY : src/core/Core.s

# target to generate assembly for a file
src/core/Core.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Core.cpp.s
.PHONY : src/core/Core.cpp.s

src/core/CoreUIObserver.o: src/core/CoreUIObserver.cpp.o
.PHONY : src/core/CoreUIObserver.o

# target to build an object file
src/core/CoreUIObserver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/CoreUIObserver.cpp.o
.PHONY : src/core/CoreUIObserver.cpp.o

src/core/CoreUIObserver.i: src/core/CoreUIObserver.cpp.i
.PHONY : src/core/CoreUIObserver.i

# target to preprocess a source file
src/core/CoreUIObserver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/CoreUIObserver.cpp.i
.PHONY : src/core/CoreUIObserver.cpp.i

src/core/CoreUIObserver.s: src/core/CoreUIObserver.cpp.s
.PHONY : src/core/CoreUIObserver.s

# target to generate assembly for a file
src/core/CoreUIObserver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/CoreUIObserver.cpp.s
.PHONY : src/core/CoreUIObserver.cpp.s

src/core/IUIObserver.o: src/core/IUIObserver.cpp.o
.PHONY : src/core/IUIObserver.o

# target to build an object file
src/core/IUIObserver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/IUIObserver.cpp.o
.PHONY : src/core/IUIObserver.cpp.o

src/core/IUIObserver.i: src/core/IUIObserver.cpp.i
.PHONY : src/core/IUIObserver.i

# target to preprocess a source file
src/core/IUIObserver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/IUIObserver.cpp.i
.PHONY : src/core/IUIObserver.cpp.i

src/core/IUIObserver.s: src/core/IUIObserver.cpp.s
.PHONY : src/core/IUIObserver.s

# target to generate assembly for a file
src/core/IUIObserver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/IUIObserver.cpp.s
.PHONY : src/core/IUIObserver.cpp.s

src/graph/Ogre.o: src/graph/Ogre.cpp.o
.PHONY : src/graph/Ogre.o

# target to build an object file
src/graph/Ogre.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/graph/Ogre.cpp.o
.PHONY : src/graph/Ogre.cpp.o

src/graph/Ogre.i: src/graph/Ogre.cpp.i
.PHONY : src/graph/Ogre.i

# target to preprocess a source file
src/graph/Ogre.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/graph/Ogre.cpp.i
.PHONY : src/graph/Ogre.cpp.i

src/graph/Ogre.s: src/graph/Ogre.cpp.s
.PHONY : src/graph/Ogre.s

# target to generate assembly for a file
src/graph/Ogre.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/graph/Ogre.cpp.s
.PHONY : src/graph/Ogre.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cpp_indie_studio"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/core/Core.o"
	@echo "... src/core/Core.i"
	@echo "... src/core/Core.s"
	@echo "... src/core/CoreUIObserver.o"
	@echo "... src/core/CoreUIObserver.i"
	@echo "... src/core/CoreUIObserver.s"
	@echo "... src/core/IUIObserver.o"
	@echo "... src/core/IUIObserver.i"
	@echo "... src/core/IUIObserver.s"
	@echo "... src/graph/Ogre.o"
	@echo "... src/graph/Ogre.i"
	@echo "... src/graph/Ogre.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

