# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/trouve_b/Desktop/CPP_project/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/trouve_b/Desktop/CPP_project/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trouve_b/Desktop/CPP_project/cpp_indie_studio/CMakeFiles /home/trouve_b/Desktop/CPP_project/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trouve_b/Desktop/CPP_project/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_indie_studio

# Build rule for target.
cpp_indie_studio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_indie_studio
.PHONY : cpp_indie_studio

# fast build rule for target.
cpp_indie_studio/fast:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/build
.PHONY : cpp_indie_studio/fast

src/World.o: src/World.cpp.o
.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i
.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s
.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/core/Core.o: src/core/Core.cpp.o
.PHONY : src/core/Core.o

# target to build an object file
src/core/Core.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Core.cpp.o
.PHONY : src/core/Core.cpp.o

src/core/Core.i: src/core/Core.cpp.i
.PHONY : src/core/Core.i

# target to preprocess a source file
src/core/Core.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Core.cpp.i
.PHONY : src/core/Core.cpp.i

src/core/Core.s: src/core/Core.cpp.s
.PHONY : src/core/Core.s

# target to generate assembly for a file
src/core/Core.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Core.cpp.s
.PHONY : src/core/Core.cpp.s

src/core/CoreUIObserver.o: src/core/CoreUIObserver.cpp.o
.PHONY : src/core/CoreUIObserver.o

# target to build an object file
src/core/CoreUIObserver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/CoreUIObserver.cpp.o
.PHONY : src/core/CoreUIObserver.cpp.o

src/core/CoreUIObserver.i: src/core/CoreUIObserver.cpp.i
.PHONY : src/core/CoreUIObserver.i

# target to preprocess a source file
src/core/CoreUIObserver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/CoreUIObserver.cpp.i
.PHONY : src/core/CoreUIObserver.cpp.i

src/core/CoreUIObserver.s: src/core/CoreUIObserver.cpp.s
.PHONY : src/core/CoreUIObserver.s

# target to generate assembly for a file
src/core/CoreUIObserver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/CoreUIObserver.cpp.s
.PHONY : src/core/CoreUIObserver.cpp.s

src/core/IUIObserver.o: src/core/IUIObserver.cpp.o
.PHONY : src/core/IUIObserver.o

# target to build an object file
src/core/IUIObserver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/IUIObserver.cpp.o
.PHONY : src/core/IUIObserver.cpp.o

src/core/IUIObserver.i: src/core/IUIObserver.cpp.i
.PHONY : src/core/IUIObserver.i

# target to preprocess a source file
src/core/IUIObserver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/IUIObserver.cpp.i
.PHONY : src/core/IUIObserver.cpp.i

src/core/IUIObserver.s: src/core/IUIObserver.cpp.s
.PHONY : src/core/IUIObserver.s

# target to generate assembly for a file
src/core/IUIObserver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/IUIObserver.cpp.s
.PHONY : src/core/IUIObserver.cpp.s

src/gameData/Actor.o: src/gameData/Actor.cpp.o
.PHONY : src/gameData/Actor.o

# target to build an object file
src/gameData/Actor.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Actor.cpp.o
.PHONY : src/gameData/Actor.cpp.o

src/gameData/Actor.i: src/gameData/Actor.cpp.i
.PHONY : src/gameData/Actor.i

# target to preprocess a source file
src/gameData/Actor.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Actor.cpp.i
.PHONY : src/gameData/Actor.cpp.i

src/gameData/Actor.s: src/gameData/Actor.cpp.s
.PHONY : src/gameData/Actor.s

# target to generate assembly for a file
src/gameData/Actor.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Actor.cpp.s
.PHONY : src/gameData/Actor.cpp.s

src/gameData/ActorPreset.o: src/gameData/ActorPreset.cpp.o
.PHONY : src/gameData/ActorPreset.o

# target to build an object file
src/gameData/ActorPreset.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/ActorPreset.cpp.o
.PHONY : src/gameData/ActorPreset.cpp.o

src/gameData/ActorPreset.i: src/gameData/ActorPreset.cpp.i
.PHONY : src/gameData/ActorPreset.i

# target to preprocess a source file
src/gameData/ActorPreset.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/ActorPreset.cpp.i
.PHONY : src/gameData/ActorPreset.cpp.i

src/gameData/ActorPreset.s: src/gameData/ActorPreset.cpp.s
.PHONY : src/gameData/ActorPreset.s

# target to generate assembly for a file
src/gameData/ActorPreset.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/ActorPreset.cpp.s
.PHONY : src/gameData/ActorPreset.cpp.s

src/gameData/ContainerObject.o: src/gameData/ContainerObject.cpp.o
.PHONY : src/gameData/ContainerObject.o

# target to build an object file
src/gameData/ContainerObject.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/ContainerObject.cpp.o
.PHONY : src/gameData/ContainerObject.cpp.o

src/gameData/ContainerObject.i: src/gameData/ContainerObject.cpp.i
.PHONY : src/gameData/ContainerObject.i

# target to preprocess a source file
src/gameData/ContainerObject.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/ContainerObject.cpp.i
.PHONY : src/gameData/ContainerObject.cpp.i

src/gameData/ContainerObject.s: src/gameData/ContainerObject.cpp.s
.PHONY : src/gameData/ContainerObject.s

# target to generate assembly for a file
src/gameData/ContainerObject.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/ContainerObject.cpp.s
.PHONY : src/gameData/ContainerObject.cpp.s

src/gameData/Creature.o: src/gameData/Creature.cpp.o
.PHONY : src/gameData/Creature.o

# target to build an object file
src/gameData/Creature.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Creature.cpp.o
.PHONY : src/gameData/Creature.cpp.o

src/gameData/Creature.i: src/gameData/Creature.cpp.i
.PHONY : src/gameData/Creature.i

# target to preprocess a source file
src/gameData/Creature.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Creature.cpp.i
.PHONY : src/gameData/Creature.cpp.i

src/gameData/Creature.s: src/gameData/Creature.cpp.s
.PHONY : src/gameData/Creature.s

# target to generate assembly for a file
src/gameData/Creature.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Creature.cpp.s
.PHONY : src/gameData/Creature.cpp.s

src/gameData/CreaturePreset.o: src/gameData/CreaturePreset.cpp.o
.PHONY : src/gameData/CreaturePreset.o

# target to build an object file
src/gameData/CreaturePreset.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/CreaturePreset.cpp.o
.PHONY : src/gameData/CreaturePreset.cpp.o

src/gameData/CreaturePreset.i: src/gameData/CreaturePreset.cpp.i
.PHONY : src/gameData/CreaturePreset.i

# target to preprocess a source file
src/gameData/CreaturePreset.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/CreaturePreset.cpp.i
.PHONY : src/gameData/CreaturePreset.cpp.i

src/gameData/CreaturePreset.s: src/gameData/CreaturePreset.cpp.s
.PHONY : src/gameData/CreaturePreset.s

# target to generate assembly for a file
src/gameData/CreaturePreset.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/CreaturePreset.cpp.s
.PHONY : src/gameData/CreaturePreset.cpp.s

src/gameData/GameObject.o: src/gameData/GameObject.cpp.o
.PHONY : src/gameData/GameObject.o

# target to build an object file
src/gameData/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/GameObject.cpp.o
.PHONY : src/gameData/GameObject.cpp.o

src/gameData/GameObject.i: src/gameData/GameObject.cpp.i
.PHONY : src/gameData/GameObject.i

# target to preprocess a source file
src/gameData/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/GameObject.cpp.i
.PHONY : src/gameData/GameObject.cpp.i

src/gameData/GameObject.s: src/gameData/GameObject.cpp.s
.PHONY : src/gameData/GameObject.s

# target to generate assembly for a file
src/gameData/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/GameObject.cpp.s
.PHONY : src/gameData/GameObject.cpp.s

src/gameData/GameObjectPreset.o: src/gameData/GameObjectPreset.cpp.o
.PHONY : src/gameData/GameObjectPreset.o

# target to build an object file
src/gameData/GameObjectPreset.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/GameObjectPreset.cpp.o
.PHONY : src/gameData/GameObjectPreset.cpp.o

src/gameData/GameObjectPreset.i: src/gameData/GameObjectPreset.cpp.i
.PHONY : src/gameData/GameObjectPreset.i

# target to preprocess a source file
src/gameData/GameObjectPreset.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/GameObjectPreset.cpp.i
.PHONY : src/gameData/GameObjectPreset.cpp.i

src/gameData/GameObjectPreset.s: src/gameData/GameObjectPreset.cpp.s
.PHONY : src/gameData/GameObjectPreset.s

# target to generate assembly for a file
src/gameData/GameObjectPreset.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/GameObjectPreset.cpp.s
.PHONY : src/gameData/GameObjectPreset.cpp.s

src/gameData/Item.o: src/gameData/Item.cpp.o
.PHONY : src/gameData/Item.o

# target to build an object file
src/gameData/Item.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Item.cpp.o
.PHONY : src/gameData/Item.cpp.o

src/gameData/Item.i: src/gameData/Item.cpp.i
.PHONY : src/gameData/Item.i

# target to preprocess a source file
src/gameData/Item.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Item.cpp.i
.PHONY : src/gameData/Item.cpp.i

src/gameData/Item.s: src/gameData/Item.cpp.s
.PHONY : src/gameData/Item.s

# target to generate assembly for a file
src/gameData/Item.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Item.cpp.s
.PHONY : src/gameData/Item.cpp.s

src/gameData/ItemContainer.o: src/gameData/ItemContainer.cpp.o
.PHONY : src/gameData/ItemContainer.o

# target to build an object file
src/gameData/ItemContainer.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/ItemContainer.cpp.o
.PHONY : src/gameData/ItemContainer.cpp.o

src/gameData/ItemContainer.i: src/gameData/ItemContainer.cpp.i
.PHONY : src/gameData/ItemContainer.i

# target to preprocess a source file
src/gameData/ItemContainer.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/ItemContainer.cpp.i
.PHONY : src/gameData/ItemContainer.cpp.i

src/gameData/ItemContainer.s: src/gameData/ItemContainer.cpp.s
.PHONY : src/gameData/ItemContainer.s

# target to generate assembly for a file
src/gameData/ItemContainer.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/ItemContainer.cpp.s
.PHONY : src/gameData/ItemContainer.cpp.s

src/gameData/LootTable.o: src/gameData/LootTable.cpp.o
.PHONY : src/gameData/LootTable.o

# target to build an object file
src/gameData/LootTable.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/LootTable.cpp.o
.PHONY : src/gameData/LootTable.cpp.o

src/gameData/LootTable.i: src/gameData/LootTable.cpp.i
.PHONY : src/gameData/LootTable.i

# target to preprocess a source file
src/gameData/LootTable.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/LootTable.cpp.i
.PHONY : src/gameData/LootTable.cpp.i

src/gameData/LootTable.s: src/gameData/LootTable.cpp.s
.PHONY : src/gameData/LootTable.s

# target to generate assembly for a file
src/gameData/LootTable.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/LootTable.cpp.s
.PHONY : src/gameData/LootTable.cpp.s

src/gameData/Player.o: src/gameData/Player.cpp.o
.PHONY : src/gameData/Player.o

# target to build an object file
src/gameData/Player.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Player.cpp.o
.PHONY : src/gameData/Player.cpp.o

src/gameData/Player.i: src/gameData/Player.cpp.i
.PHONY : src/gameData/Player.i

# target to preprocess a source file
src/gameData/Player.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Player.cpp.i
.PHONY : src/gameData/Player.cpp.i

src/gameData/Player.s: src/gameData/Player.cpp.s
.PHONY : src/gameData/Player.s

# target to generate assembly for a file
src/gameData/Player.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Player.cpp.s
.PHONY : src/gameData/Player.cpp.s

src/gameData/PlayerPreset.o: src/gameData/PlayerPreset.cpp.o
.PHONY : src/gameData/PlayerPreset.o

# target to build an object file
src/gameData/PlayerPreset.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/PlayerPreset.cpp.o
.PHONY : src/gameData/PlayerPreset.cpp.o

src/gameData/PlayerPreset.i: src/gameData/PlayerPreset.cpp.i
.PHONY : src/gameData/PlayerPreset.i

# target to preprocess a source file
src/gameData/PlayerPreset.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/PlayerPreset.cpp.i
.PHONY : src/gameData/PlayerPreset.cpp.i

src/gameData/PlayerPreset.s: src/gameData/PlayerPreset.cpp.s
.PHONY : src/gameData/PlayerPreset.s

# target to generate assembly for a file
src/gameData/PlayerPreset.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/PlayerPreset.cpp.s
.PHONY : src/gameData/PlayerPreset.cpp.s

src/gameData/Spell.o: src/gameData/Spell.cpp.o
.PHONY : src/gameData/Spell.o

# target to build an object file
src/gameData/Spell.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Spell.cpp.o
.PHONY : src/gameData/Spell.cpp.o

src/gameData/Spell.i: src/gameData/Spell.cpp.i
.PHONY : src/gameData/Spell.i

# target to preprocess a source file
src/gameData/Spell.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Spell.cpp.i
.PHONY : src/gameData/Spell.cpp.i

src/gameData/Spell.s: src/gameData/Spell.cpp.s
.PHONY : src/gameData/Spell.s

# target to generate assembly for a file
src/gameData/Spell.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Spell.cpp.s
.PHONY : src/gameData/Spell.cpp.s

src/gameData/SpellContainer.o: src/gameData/SpellContainer.cpp.o
.PHONY : src/gameData/SpellContainer.o

# target to build an object file
src/gameData/SpellContainer.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/SpellContainer.cpp.o
.PHONY : src/gameData/SpellContainer.cpp.o

src/gameData/SpellContainer.i: src/gameData/SpellContainer.cpp.i
.PHONY : src/gameData/SpellContainer.i

# target to preprocess a source file
src/gameData/SpellContainer.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/SpellContainer.cpp.i
.PHONY : src/gameData/SpellContainer.cpp.i

src/gameData/SpellContainer.s: src/gameData/SpellContainer.cpp.s
.PHONY : src/gameData/SpellContainer.s

# target to generate assembly for a file
src/gameData/SpellContainer.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/SpellContainer.cpp.s
.PHONY : src/gameData/SpellContainer.cpp.s

src/gameData/Stats.o: src/gameData/Stats.cpp.o
.PHONY : src/gameData/Stats.o

# target to build an object file
src/gameData/Stats.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Stats.cpp.o
.PHONY : src/gameData/Stats.cpp.o

src/gameData/Stats.i: src/gameData/Stats.cpp.i
.PHONY : src/gameData/Stats.i

# target to preprocess a source file
src/gameData/Stats.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Stats.cpp.i
.PHONY : src/gameData/Stats.cpp.i

src/gameData/Stats.s: src/gameData/Stats.cpp.s
.PHONY : src/gameData/Stats.s

# target to generate assembly for a file
src/gameData/Stats.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/gameData/Stats.cpp.s
.PHONY : src/gameData/Stats.cpp.s

src/graph/Ogre.o: src/graph/Ogre.cpp.o
.PHONY : src/graph/Ogre.o

# target to build an object file
src/graph/Ogre.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/graph/Ogre.cpp.o
.PHONY : src/graph/Ogre.cpp.o

src/graph/Ogre.i: src/graph/Ogre.cpp.i
.PHONY : src/graph/Ogre.i

# target to preprocess a source file
src/graph/Ogre.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/graph/Ogre.cpp.i
.PHONY : src/graph/Ogre.cpp.i

src/graph/Ogre.s: src/graph/Ogre.cpp.s
.PHONY : src/graph/Ogre.s

# target to generate assembly for a file
src/graph/Ogre.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/graph/Ogre.cpp.s
.PHONY : src/graph/Ogre.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cpp_indie_studio"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/core/Core.o"
	@echo "... src/core/Core.i"
	@echo "... src/core/Core.s"
	@echo "... src/core/CoreUIObserver.o"
	@echo "... src/core/CoreUIObserver.i"
	@echo "... src/core/CoreUIObserver.s"
	@echo "... src/core/IUIObserver.o"
	@echo "... src/core/IUIObserver.i"
	@echo "... src/core/IUIObserver.s"
	@echo "... src/gameData/Actor.o"
	@echo "... src/gameData/Actor.i"
	@echo "... src/gameData/Actor.s"
	@echo "... src/gameData/ActorPreset.o"
	@echo "... src/gameData/ActorPreset.i"
	@echo "... src/gameData/ActorPreset.s"
	@echo "... src/gameData/ContainerObject.o"
	@echo "... src/gameData/ContainerObject.i"
	@echo "... src/gameData/ContainerObject.s"
	@echo "... src/gameData/Creature.o"
	@echo "... src/gameData/Creature.i"
	@echo "... src/gameData/Creature.s"
	@echo "... src/gameData/CreaturePreset.o"
	@echo "... src/gameData/CreaturePreset.i"
	@echo "... src/gameData/CreaturePreset.s"
	@echo "... src/gameData/GameObject.o"
	@echo "... src/gameData/GameObject.i"
	@echo "... src/gameData/GameObject.s"
	@echo "... src/gameData/GameObjectPreset.o"
	@echo "... src/gameData/GameObjectPreset.i"
	@echo "... src/gameData/GameObjectPreset.s"
	@echo "... src/gameData/Item.o"
	@echo "... src/gameData/Item.i"
	@echo "... src/gameData/Item.s"
	@echo "... src/gameData/ItemContainer.o"
	@echo "... src/gameData/ItemContainer.i"
	@echo "... src/gameData/ItemContainer.s"
	@echo "... src/gameData/LootTable.o"
	@echo "... src/gameData/LootTable.i"
	@echo "... src/gameData/LootTable.s"
	@echo "... src/gameData/Player.o"
	@echo "... src/gameData/Player.i"
	@echo "... src/gameData/Player.s"
	@echo "... src/gameData/PlayerPreset.o"
	@echo "... src/gameData/PlayerPreset.i"
	@echo "... src/gameData/PlayerPreset.s"
	@echo "... src/gameData/Spell.o"
	@echo "... src/gameData/Spell.i"
	@echo "... src/gameData/Spell.s"
	@echo "... src/gameData/SpellContainer.o"
	@echo "... src/gameData/SpellContainer.i"
	@echo "... src/gameData/SpellContainer.s"
	@echo "... src/gameData/Stats.o"
	@echo "... src/gameData/Stats.i"
	@echo "... src/gameData/Stats.s"
	@echo "... src/graph/Ogre.o"
	@echo "... src/graph/Ogre.i"
	@echo "... src/graph/Ogre.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

