# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lewis_e/rendu/cpp/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lewis_e/rendu/cpp/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lewis_e/rendu/cpp/cpp_indie_studio/CMakeFiles /home/lewis_e/rendu/cpp/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lewis_e/rendu/cpp/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_indie_studio

# Build rule for target.
cpp_indie_studio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_indie_studio
.PHONY : cpp_indie_studio

# fast build rule for target.
cpp_indie_studio/fast:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/build
.PHONY : cpp_indie_studio/fast

src/core/Core.o: src/core/Core.cpp.o
.PHONY : src/core/Core.o

# target to build an object file
src/core/Core.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Core.cpp.o
.PHONY : src/core/Core.cpp.o

src/core/Core.i: src/core/Core.cpp.i
.PHONY : src/core/Core.i

# target to preprocess a source file
src/core/Core.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Core.cpp.i
.PHONY : src/core/Core.cpp.i

src/core/Core.s: src/core/Core.cpp.s
.PHONY : src/core/Core.s

# target to generate assembly for a file
src/core/Core.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Core.cpp.s
.PHONY : src/core/Core.cpp.s

src/core/CoreUIObserver.o: src/core/CoreUIObserver.cpp.o
.PHONY : src/core/CoreUIObserver.o

# target to build an object file
src/core/CoreUIObserver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/CoreUIObserver.cpp.o
.PHONY : src/core/CoreUIObserver.cpp.o

src/core/CoreUIObserver.i: src/core/CoreUIObserver.cpp.i
.PHONY : src/core/CoreUIObserver.i

# target to preprocess a source file
src/core/CoreUIObserver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/CoreUIObserver.cpp.i
.PHONY : src/core/CoreUIObserver.cpp.i

src/core/CoreUIObserver.s: src/core/CoreUIObserver.cpp.s
.PHONY : src/core/CoreUIObserver.s

# target to generate assembly for a file
src/core/CoreUIObserver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/CoreUIObserver.cpp.s
.PHONY : src/core/CoreUIObserver.cpp.s

src/core/MainMenu.o: src/core/MainMenu.cpp.o
.PHONY : src/core/MainMenu.o

# target to build an object file
src/core/MainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/MainMenu.cpp.o
.PHONY : src/core/MainMenu.cpp.o

src/core/MainMenu.i: src/core/MainMenu.cpp.i
.PHONY : src/core/MainMenu.i

# target to preprocess a source file
src/core/MainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/MainMenu.cpp.i
.PHONY : src/core/MainMenu.cpp.i

src/core/MainMenu.s: src/core/MainMenu.cpp.s
.PHONY : src/core/MainMenu.s

# target to generate assembly for a file
src/core/MainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/MainMenu.cpp.s
.PHONY : src/core/MainMenu.cpp.s

src/core/Menu.o: src/core/Menu.cpp.o
.PHONY : src/core/Menu.o

# target to build an object file
src/core/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Menu.cpp.o
.PHONY : src/core/Menu.cpp.o

src/core/Menu.i: src/core/Menu.cpp.i
.PHONY : src/core/Menu.i

# target to preprocess a source file
src/core/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Menu.cpp.i
.PHONY : src/core/Menu.cpp.i

src/core/Menu.s: src/core/Menu.cpp.s
.PHONY : src/core/Menu.s

# target to generate assembly for a file
src/core/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Menu.cpp.s
.PHONY : src/core/Menu.cpp.s

src/core/MenuButton.o: src/core/MenuButton.cpp.o
.PHONY : src/core/MenuButton.o

# target to build an object file
src/core/MenuButton.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/MenuButton.cpp.o
.PHONY : src/core/MenuButton.cpp.o

src/core/MenuButton.i: src/core/MenuButton.cpp.i
.PHONY : src/core/MenuButton.i

# target to preprocess a source file
src/core/MenuButton.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/MenuButton.cpp.i
.PHONY : src/core/MenuButton.cpp.i

src/core/MenuButton.s: src/core/MenuButton.cpp.s
.PHONY : src/core/MenuButton.s

# target to generate assembly for a file
src/core/MenuButton.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/MenuButton.cpp.s
.PHONY : src/core/MenuButton.cpp.s

src/core/PlayerController.o: src/core/PlayerController.cpp.o
.PHONY : src/core/PlayerController.o

# target to build an object file
src/core/PlayerController.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/PlayerController.cpp.o
.PHONY : src/core/PlayerController.cpp.o

src/core/PlayerController.i: src/core/PlayerController.cpp.i
.PHONY : src/core/PlayerController.i

# target to preprocess a source file
src/core/PlayerController.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/PlayerController.cpp.i
.PHONY : src/core/PlayerController.cpp.i

src/core/PlayerController.s: src/core/PlayerController.cpp.s
.PHONY : src/core/PlayerController.s

# target to generate assembly for a file
src/core/PlayerController.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/PlayerController.cpp.s
.PHONY : src/core/PlayerController.cpp.s

src/core/SaveloadMenu.o: src/core/SaveloadMenu.cpp.o
.PHONY : src/core/SaveloadMenu.o

# target to build an object file
src/core/SaveloadMenu.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/SaveloadMenu.cpp.o
.PHONY : src/core/SaveloadMenu.cpp.o

src/core/SaveloadMenu.i: src/core/SaveloadMenu.cpp.i
.PHONY : src/core/SaveloadMenu.i

# target to preprocess a source file
src/core/SaveloadMenu.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/SaveloadMenu.cpp.i
.PHONY : src/core/SaveloadMenu.cpp.i

src/core/SaveloadMenu.s: src/core/SaveloadMenu.cpp.s
.PHONY : src/core/SaveloadMenu.s

# target to generate assembly for a file
src/core/SaveloadMenu.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/SaveloadMenu.cpp.s
.PHONY : src/core/SaveloadMenu.cpp.s

src/core/Stopwatch.o: src/core/Stopwatch.cpp.o
.PHONY : src/core/Stopwatch.o

# target to build an object file
src/core/Stopwatch.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Stopwatch.cpp.o
.PHONY : src/core/Stopwatch.cpp.o

src/core/Stopwatch.i: src/core/Stopwatch.cpp.i
.PHONY : src/core/Stopwatch.i

# target to preprocess a source file
src/core/Stopwatch.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Stopwatch.cpp.i
.PHONY : src/core/Stopwatch.cpp.i

src/core/Stopwatch.s: src/core/Stopwatch.cpp.s
.PHONY : src/core/Stopwatch.s

# target to generate assembly for a file
src/core/Stopwatch.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/core/Stopwatch.cpp.s
.PHONY : src/core/Stopwatch.cpp.s

src/graph/Ogre.o: src/graph/Ogre.cpp.o
.PHONY : src/graph/Ogre.o

# target to build an object file
src/graph/Ogre.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/graph/Ogre.cpp.o
.PHONY : src/graph/Ogre.cpp.o

src/graph/Ogre.i: src/graph/Ogre.cpp.i
.PHONY : src/graph/Ogre.i

# target to preprocess a source file
src/graph/Ogre.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/graph/Ogre.cpp.i
.PHONY : src/graph/Ogre.cpp.i

src/graph/Ogre.s: src/graph/Ogre.cpp.s
.PHONY : src/graph/Ogre.s

# target to generate assembly for a file
src/graph/Ogre.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/graph/Ogre.cpp.s
.PHONY : src/graph/Ogre.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/world/World.o: src/world/World.cpp.o
.PHONY : src/world/World.o

# target to build an object file
src/world/World.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/world/World.cpp.o
.PHONY : src/world/World.cpp.o

src/world/World.i: src/world/World.cpp.i
.PHONY : src/world/World.i

# target to preprocess a source file
src/world/World.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/world/World.cpp.i
.PHONY : src/world/World.cpp.i

src/world/World.s: src/world/World.cpp.s
.PHONY : src/world/World.s

# target to generate assembly for a file
src/world/World.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_indie_studio.dir/build.make CMakeFiles/cpp_indie_studio.dir/src/world/World.cpp.s
.PHONY : src/world/World.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cpp_indie_studio"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/core/Core.o"
	@echo "... src/core/Core.i"
	@echo "... src/core/Core.s"
	@echo "... src/core/CoreUIObserver.o"
	@echo "... src/core/CoreUIObserver.i"
	@echo "... src/core/CoreUIObserver.s"
	@echo "... src/core/MainMenu.o"
	@echo "... src/core/MainMenu.i"
	@echo "... src/core/MainMenu.s"
	@echo "... src/core/Menu.o"
	@echo "... src/core/Menu.i"
	@echo "... src/core/Menu.s"
	@echo "... src/core/MenuButton.o"
	@echo "... src/core/MenuButton.i"
	@echo "... src/core/MenuButton.s"
	@echo "... src/core/PlayerController.o"
	@echo "... src/core/PlayerController.i"
	@echo "... src/core/PlayerController.s"
	@echo "... src/core/SaveloadMenu.o"
	@echo "... src/core/SaveloadMenu.i"
	@echo "... src/core/SaveloadMenu.s"
	@echo "... src/core/Stopwatch.o"
	@echo "... src/core/Stopwatch.i"
	@echo "... src/core/Stopwatch.s"
	@echo "... src/graph/Ogre.o"
	@echo "... src/graph/Ogre.i"
	@echo "... src/graph/Ogre.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/world/World.o"
	@echo "... src/world/World.i"
	@echo "... src/world/World.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

