//
// Created by drouar_b on 5/24/16.
//

#include <OIS/OIS.h>
#include "graph/OgreUI.hh"

const std::map<OIS::KeyCode, gauntlet::core::IUIObserver::Key> OgreUI::keymap = {
	{OIS::KC_UP,        gauntlet::core::IUIObserver::KEY_UP},
	{OIS::KC_DOWN,      gauntlet::core::IUIObserver::KEY_DOWN},
	{OIS::KC_RIGHT,     gauntlet::core::IUIObserver::KEY_RIGHT},
	{OIS::KC_LEFT,      gauntlet::core::IUIObserver::KEY_LEFT},
	{OIS::KC_ESCAPE,    gauntlet::core::IUIObserver::KEY_ESC},
	{OIS::KC_TAB,       gauntlet::core::IUIObserver::KEY_TAB},
	{OIS::KC_SPACE,     gauntlet::core::IUIObserver::KEY_SPACE},
	{OIS::KC_BACK,      gauntlet::core::IUIObserver::KEY_BACK},
	{OIS::KC_A,         gauntlet::core::IUIObserver::KEY_A},
	{OIS::KC_B,         gauntlet::core::IUIObserver::KEY_B},
	{OIS::KC_C,         gauntlet::core::IUIObserver::KEY_C},
	{OIS::KC_D,         gauntlet::core::IUIObserver::KEY_D},
	{OIS::KC_E,         gauntlet::core::IUIObserver::KEY_E},
	{OIS::KC_F,         gauntlet::core::IUIObserver::KEY_F},
	{OIS::KC_RETURN,    gauntlet::core::IUIObserver::KEY_ENTER},
	{OIS::KC_G,         gauntlet::core::IUIObserver::KEY_G},
	{OIS::KC_H,         gauntlet::core::IUIObserver::KEY_H},
	{OIS::KC_I,         gauntlet::core::IUIObserver::KEY_I},
	{OIS::KC_J,         gauntlet::core::IUIObserver::KEY_J},
	{OIS::KC_K,         gauntlet::core::IUIObserver::KEY_K},
	{OIS::KC_L,         gauntlet::core::IUIObserver::KEY_L},
	{OIS::KC_M,         gauntlet::core::IUIObserver::KEY_M},
	{OIS::KC_N,         gauntlet::core::IUIObserver::KEY_N},
	{OIS::KC_O,         gauntlet::core::IUIObserver::KEY_O},
	{OIS::KC_P,         gauntlet::core::IUIObserver::KEY_P},
	{OIS::KC_Q,         gauntlet::core::IUIObserver::KEY_Q},
	{OIS::KC_R,         gauntlet::core::IUIObserver::KEY_R},
	{OIS::KC_S,         gauntlet::core::IUIObserver::KEY_S},
	{OIS::KC_T,         gauntlet::core::IUIObserver::KEY_T},
	{OIS::KC_U,         gauntlet::core::IUIObserver::KEY_U},
	{OIS::KC_V,         gauntlet::core::IUIObserver::KEY_V},
	{OIS::KC_W,         gauntlet::core::IUIObserver::KEY_W},
	{OIS::KC_X,         gauntlet::core::IUIObserver::KEY_X},
	{OIS::KC_Y,         gauntlet::core::IUIObserver::KEY_Y},
	{OIS::KC_Z,         gauntlet::core::IUIObserver::KEY_Z},

	{OIS::KC_0,         gauntlet::core::IUIObserver::KEY_0},
	{OIS::KC_1,         gauntlet::core::IUIObserver::KEY_1},
	{OIS::KC_2,         gauntlet::core::IUIObserver::KEY_2},
	{OIS::KC_3,         gauntlet::core::IUIObserver::KEY_3},
	{OIS::KC_4,         gauntlet::core::IUIObserver::KEY_4},
	{OIS::KC_5,         gauntlet::core::IUIObserver::KEY_5},
	{OIS::KC_6,         gauntlet::core::IUIObserver::KEY_6},
	{OIS::KC_7,         gauntlet::core::IUIObserver::KEY_7},
	{OIS::KC_8,         gauntlet::core::IUIObserver::KEY_8},
	{OIS::KC_9,         gauntlet::core::IUIObserver::KEY_9},

	{OIS::KC_NUMPAD0,   gauntlet::core::IUIObserver::KEY_0},
	{OIS::KC_NUMPAD1,   gauntlet::core::IUIObserver::KEY_1},
	{OIS::KC_NUMPAD2,   gauntlet::core::IUIObserver::KEY_2},
	{OIS::KC_NUMPAD3,   gauntlet::core::IUIObserver::KEY_3},
	{OIS::KC_NUMPAD4,   gauntlet::core::IUIObserver::KEY_4},
	{OIS::KC_NUMPAD5,   gauntlet::core::IUIObserver::KEY_5},
	{OIS::KC_NUMPAD6,   gauntlet::core::IUIObserver::KEY_6},
	{OIS::KC_NUMPAD7,   gauntlet::core::IUIObserver::KEY_7},
	{OIS::KC_NUMPAD8,   gauntlet::core::IUIObserver::KEY_8},
	{OIS::KC_NUMPAD9,   gauntlet::core::IUIObserver::KEY_9},
	{OIS::KC_PERIOD,    gauntlet::core::IUIObserver::KEY_PERIOD},
	{OIS::KC_SEMICOLON, gauntlet::core::IUIObserver::KEY_PERIOD}
};

const std::map<OIS::MouseButtonID, gauntlet::core::IUIObserver::Key> OgreUI::mousemap = {
	{OIS::MB_Left,  gauntlet::core::IUIObserver::KEY_MOUSE1},
	{OIS::MB_Right, gauntlet::core::IUIObserver::KEY_MOUSE2}
};

const std::map<gauntlet::BackgroundName, std::string> OgreUI::backgroundmap = {
	{gauntlet::BackgroundName::BACKGROUND_DOOR,    "Ogre/BackgroundDoor"},
	{gauntlet::BackgroundName::BACKGROUND_PLAYERS, "Ogre/BackgroundPlayers"},
	{gauntlet::BackgroundName::BACKGROUND_ROOM,    "Ogre/BackgroundRoom"},
	{gauntlet::BackgroundName::BACKGROUND_CAVE,    "Ogre/BackgroundCave"},
	{gauntlet::BackgroundName::BACKGROUND_HELL,    "Ogre/BackgroundHell"},
	{gauntlet::BackgroundName::BACKGROUND_BASIC,   "Ogre/Background"}
};
const std::map<gauntlet::core::Position, OgreBites::TrayLocation> OgreUI::posmap = {
	{gauntlet::core::PCENTER,      OgreBites::TL_CENTER},
	{gauntlet::core::PTOPRIGHT,    OgreBites::TL_TOPRIGHT},
	{gauntlet::core::PTOPLEFT,     OgreBites::TL_TOPLEFT},
	{gauntlet::core::PTOP,         OgreBites::TL_TOP},
	{gauntlet::core::PBOTTOM,      OgreBites::TL_BOTTOM},
	{gauntlet::core::PBOTTOMLEFT,  OgreBites::TL_BOTTOMLEFT},
	{gauntlet::core::PBOTTOMRIGHT, OgreBites::TL_BOTTOMRIGHT},
	{gauntlet::core::PRIGHT,       OgreBites::TL_RIGHT},
	{gauntlet::core::PLEFT,        OgreBites::TL_LEFT}
};

const std::map<gauntlet::EntityName, std::string> OgreUI::meshmap = {
	{gauntlet::EntityName::OGREHEAD,          "unityexportmap_obj.mesh"},
	{gauntlet::EntityName::NINJA,             "ninja.mesh"},
	{gauntlet::EntityName::PLAN,              "plan.mesh"},
	{gauntlet::EntityName::TUDORHOUSE,        "tudorhouse.mesh"},
	{gauntlet::EntityName::DOOR,              "wood_door.mesh"},
	{gauntlet::EntityName::CUBE,              "cube.mesh"},
	{gauntlet::EntityName::ROCK,              "Rock.mesh"},
	{gauntlet::EntityName::CHEST,             "Chest2B.mesh"},
	{gauntlet::EntityName::BERSERK,           "berserker.mesh"},
	{gauntlet::EntityName::VALKYRIE,          "girl_warrior.mesh"},
	{gauntlet::EntityName::CHESTCARTOON,      "chestCartoon.mesh"},
	{gauntlet::EntityName::WAGEN,             "wagen.mesh"},
	{gauntlet::EntityName::MAP_TEST,          "map_of_doom.mesh"},
	{gauntlet::EntityName::TROLL,             "troll.mesh"},
	{gauntlet::EntityName::SKELETON_ARCHER,   "skeleton_archer.mesh"},
	{gauntlet::EntityName::SKELETON_FOOTMAN,  "skeleton_footman.mesh"},
	{gauntlet::EntityName::SKELETON_SORCERER, "skeleton_sorcerer.mesh"},
	{gauntlet::EntityName::SKELETON_WARLORD,  "skeleton_warlord.mesh"}
};

const std::map<gauntlet::TextureName, std::string> OgreUI::texturemap = {
	{gauntlet::TextureName::NINjA_M,      "Plan/sol"},
	{gauntlet::TextureName::TUDORHOUSE_M, "TudorHouse/house"}
};

const std::map<gauntlet::CharacterMenuName, std::string> OgreUI::charactermap = {
	{gauntlet::CharacterMenuName::BERSERKER_MENU_SELECTION, "Character/Berserker_menu_selection"},
	{gauntlet::CharacterMenuName::MAGUS_MENU_SELECTION,     "Character/Magus_menu_selection"},
	{gauntlet::CharacterMenuName::RANGER_MENU_SELECTION,    "Character/Ranger_menu_selection"},
	{gauntlet::CharacterMenuName::VALKYRIE_MENU_SELECTION,  "Character/Valkyrie_menu_selection"}
};

const std::map<gauntlet::SoundName, std::string>OgreUI::soundmap = {
	{gauntlet::SoundName::MENU_SOUND,               "menu_theme.ogg"},
	{gauntlet::SoundName::AMBIENT_DARKCORRIDORS,    "Ambient - dark corridors.ogg"},
	{gauntlet::SoundName::AMBIENT_UNDERLAND,        "Ambient - underland.ogg"},
	{gauntlet::SoundName::AMBIENT_SEWERS,           "Ambient - sewers.ogg"},
	{gauntlet::SoundName::AMBIENT_LAVA,             "Ambient - lava.ogg"},
	{gauntlet::SoundName::AXE_HIT_SPROSH,           "Axe 1.ogg"},
	{gauntlet::SoundName::AXE_HIT_SOFT,             "Axe 2.ogg"},
	{gauntlet::SoundName::AXE_HIT_HARD,             "Axe 3.ogg"},
	{gauntlet::SoundName::BATS_1,                   "Bats 1.ogg"},
	{gauntlet::SoundName::BATS_2,                   "Bats 2.ogg"},
	{gauntlet::SoundName::BATS_LOOP,                "Bats (loop).ogg"},
	{gauntlet::SoundName::BOW,                      "Bow 1.ogg"},
	{gauntlet::SoundName::BUTTON,                   "Button 3.ogg"},
	{gauntlet::SoundName::COIN_BAG,                 "Coins (bag).ogg"},
	{gauntlet::SoundName::COINS,                    "Coins.ogg"},
	{gauntlet::SoundName::DOOR_METAL_CLOSE,         "Door 1 (metal close).ogg"},
	{gauntlet::SoundName::DOOR_METAL_OPEN,          "Door 1 (metal open).ogg"},
	{gauntlet::SoundName::DOOR_WOOD_CLOSE,          "Door 2 (wood close).ogg"},
	{gauntlet::SoundName::DOOR_WOOD_OPEN,           "Door 2 (wood open).ogg"},
	{gauntlet::SoundName::DOOR_STONE,               "Door 3 (stone).ogg"},
	{gauntlet::SoundName::DOOR_GATE,                "Door 4 (big gate).ogg"},
	{gauntlet::SoundName::EVENT_VICTORY,            "Event 1.ogg"},
	{gauntlet::SoundName::EVENT_DRAMATIC,           "Event 2.ogg"},
	{gauntlet::SoundName::EVENT_DISCOVERY,          "Event 3.ogg"},
	{gauntlet::SoundName::EVENT_DRUMS,              "Event 4.ogg"},
	{gauntlet::SoundName::EVENT_MYSTERY,            "Event 9.ogg"},
	{gauntlet::SoundName::HAMMER_HIT_HARD,          "Hammer 1.ogg"},
	{gauntlet::SoundName::HAMMER_HIT_SOFT,          "Hammer 2.ogg"},
	{gauntlet::SoundName::MAP_CLOSE,                "Map (close).ogg"},
	{gauntlet::SoundName::MAP_OPEN,                 "Map (open).ogg"},
	{gauntlet::SoundName::MUSIC_COMBAT_DRAMATIC,    "Music - dramatic combat.ogg"},
	{gauntlet::SoundName::MUSIC_MASSACRE,           "Music - massacre.ogg"},
	{gauntlet::SoundName::MUSIC_MYSTERIOUS_CAVERNS, "Music - mysterious caverns.ogg"},
	{gauntlet::SoundName::MUSIC_TERROR,             "Music - terror.ogg"},
	{gauntlet::SoundName::MUSIC_MINES,              "Music - through the mines.ogg"},
	{gauntlet::SoundName::MUSIC_UNDERGROUND,        "Music - underground route.ogg"},
	{gauntlet::SoundName::SPIKE_TRAP_1,             "Spiked Trap 1.ogg"},
	{gauntlet::SoundName::SPIKE_TRAP_2,             "Spiked Trap 2.ogg"},
	{gauntlet::SoundName::STEP_STONE_1,             "Step 10 (stone).ogg"},
	{gauntlet::SoundName::STEP_STONE_2,             "Step 11 (stone).ogg"},
	{gauntlet::SoundName::STEP_STONE_3,             "Step 12 (stone).ogg"},
	{gauntlet::SoundName::STEP_STONE_4,             "Step 9 (stone).ogg"},
	{gauntlet::SoundName::SWORD_HIT,                "Sword 1.ogg"},
	{gauntlet::SoundName::SWORD_DRAW,               "Sword 3.ogg"},
	{gauntlet::SoundName::FIRE_SMALL,               "Torch 1 (loop).ogg"},
	{gauntlet::SoundName::FIRE_BIG,                 "Torch 2 (loop).ogg"},
	{gauntlet::SoundName::CORPSE,                   "Treasure Chest (bones).ogg"},
	{gauntlet::SoundName::TREASURE_OPEN,            "Treasure Chest (close)(1).ogg"},
	{gauntlet::SoundName::TREASURE_CLOSE,           "Treasure Chest (open).ogg"},
	{gauntlet::SoundName::RUBBISH,                  "Treasure Chest (rubbish).ogg"},
	{gauntlet::SoundName::WATER_DROP,               "Water Drop 1.ogg"},
	{gauntlet::SoundName::MONSTER_1,                "Beast 1.ogg"},
	{gauntlet::SoundName::MONSTER_2,                "Beast 2.ogg"},
	{gauntlet::SoundName::MONSTER_3,                "Beast 3.ogg"},
	{gauntlet::SoundName::MONSTER_4,                "Beast 4.ogg"},
	{gauntlet::SoundName::MONSTER_5,                "Beast 5.ogg"},
	{gauntlet::SoundName::BEAST_1,                  "Beast Roar 1.ogg"},
	{gauntlet::SoundName::BEAST_2,                  "Beast Roar 2.ogg"},
	{gauntlet::SoundName::BEAST_3,                  "Beast Roar 3.ogg"},
	{gauntlet::SoundName::BEAST_BIG_1,              "Big Beast Roar 1.ogg"},
	{gauntlet::SoundName::BEAST_BIG_2,              "Big Beast Roar 2.ogg"},
	{gauntlet::SoundName::CREATURE_1,               "Creature 1 (insect).ogg"},
	{gauntlet::SoundName::CREATURE_2,               "Creature 2 (insect).ogg"},
	{gauntlet::SoundName::CREATURE_3,               "Creature 3 (insect).ogg"},
	{gauntlet::SoundName::CREATURE_4,               "Creature 4 (insect).ogg"},
	{gauntlet::SoundName::CREATURE_5,               "Creature 5 (insect).ogg"},
	{gauntlet::SoundName::FEMALE_HEAVY_ATTACK,      "Female Voice 10 (heavy attack).ogg"},
	{gauntlet::SoundName::FEMALE_DEATH,             "Female Voice 5 (death).ogg"},
	{gauntlet::SoundName::FEMALE_ATTACK,            "Female Voice 6 (attack).ogg"},
	{gauntlet::SoundName::FEMALE_DOUBLE_ATTACK,     "Female Voice 7 (double attack).ogg"},
	{gauntlet::SoundName::FEMALE_HEAVY_ATTACK_2,    "Female Voice 4 (heavy attack).ogg"},
	{gauntlet::SoundName::FEMALE_HEAVY_ATTACK_3,    "Female Voice 8 (heavy attack).ogg"},
	{gauntlet::SoundName::FEMALE_HEAVY_ATTACK_4,    "Female Voice 9 (heavy attack).ogg"},
	{gauntlet::SoundName::LITTLE_CREATURE_1,        "Little Creature 1.ogg"},
	{gauntlet::SoundName::LITTLE_CREATURE_2,        "Little Creature 2.ogg"},
	{gauntlet::SoundName::LITTLE_CREATURE_3,        "Little Creature 3.ogg"},
	{gauntlet::SoundName::LITTLE_CREATURE_4,        "Little Creature 4.ogg"},
	{gauntlet::SoundName::MALE_ATTACK_1,            "Male Voice A 1 (attack).ogg"},
	{gauntlet::SoundName::MALE_ATTACK_2,            "Male Voice A 2 (attack).ogg"},
	{gauntlet::SoundName::MALE_DEATH,               "Male Voice A 3 (death).ogg"},
	{gauntlet::SoundName::MALE_WOUNDED,             "Male Voice A 4 (wounded).ogg"},
	{gauntlet::SoundName::MALE_HEAVY_ATTACK,        "Male Voice A 5 (heavy attack).ogg"},
	{gauntlet::SoundName::MALE_HEAVY_ATTACK_2,      "Male Voice A 6 (heavy attack).ogg"},
	{gauntlet::SoundName::MALE_2_HEAVY_ATTACK,      "Male Voice B 1 (heavy attack).ogg"},
	{gauntlet::SoundName::MALE_2_WOUNDED,           "Male Voice B 3 (wounded).ogg"},
	{gauntlet::SoundName::MALE_2_HEAVY_ATTACK,      "Male Voice B 4 (heavy attack).ogg"},
	{gauntlet::SoundName::MALE_2_DOUBLE_ATTACK,     "Male Voice B 5 (double attack).ogg"},
	{gauntlet::SoundName::MALE_2_DEATH,             "Male Voice B 6 (death).ogg"},
	{gauntlet::SoundName::ZOMBIE_1,                 "Phantom 1.ogg"},
	{gauntlet::SoundName::ZOMBIE_2,                 "Phantom 2.ogg"},
	{gauntlet::SoundName::ZOMBIE_3,                 "Phantom 3.ogg"},
	{gauntlet::SoundName::GHOST_1,                  "Spirit 1.ogg"},
	{gauntlet::SoundName::GHOST_2,                  "Spirit 2.ogg"},
	{gauntlet::SoundName::GHOST_3,                  "Spirit 3.ogg"},
	{gauntlet::SoundName::GHOST_4,                  "Spirit 4.ogg"},
	{gauntlet::SoundName::GHOST_5,                  "Spirit 5.ogg"},
	{gauntlet::SoundName::GHOST_6,                  "Spirit 6.ogg"},
	{gauntlet::SoundName::MAGIC_REGENERATION,       "mag_alteration_detectlife_cast_2d_lpm.ogg"},
	{gauntlet::SoundName::MAGIC_ARMOR,              "mag_alteration_ironflesh_fire.ogg"},
	{gauntlet::SoundName::MAGIC_CLOAK_IN,           "mag_alteration_release.ogg"},
	{gauntlet::SoundName::MAGIC_CLOAK_OUT,          "mag_cloak_in.ogg"},
	{gauntlet::SoundName::MAGIC_BREAK,              "mag_cloak_out.ogg"},
	{gauntlet::SoundName::MAGIC_EXPLOSION_1,        "mag_destruction_fireball_explosion_01.ogg"},
	{gauntlet::SoundName::MAGIC_EXPLOSION_2,        "mag_destruction_fireball_explosion_02.ogg"},
	{gauntlet::SoundName::MAGIC_EFFECT,             "mag_firebolt_fire_2d.ogg"},
	{gauntlet::SoundName::MAGIC_ICICLE,             "mag_icicle_fire.ogg"},
	{gauntlet::SoundName::MAGIC_EFFECT_2,           "mag_illusion_charm_on_01.ogg"},
	{gauntlet::SoundName::MAGIC_INVISIBILITY,       "mag_illusion_invisibility_in.ogg"},
	{gauntlet::SoundName::MAGIC_RELEASE,            "mag_illusion_release_01.ogg"},
	{gauntlet::SoundName::MAGIC_EFFECT_3,           "mag_nightingale_strife_fire_2d.ogg"},
	{gauntlet::SoundName::MAGIC_SHADOW,             "mag_perk_shadowwarrior_fire_2d.ogg"},
	{gauntlet::SoundName::MAGIC_CLASH,              "mag_perk_shieldcharge_impact_01.ogg"},
	{gauntlet::SoundName::MAGIC_BATTLECRY,          "mag_powerracial_battlecry_fire_2d.ogg"},
	{gauntlet::SoundName::MAGIC_BERSERKER,          "mag_powerracial_berserker_fire_2d.ogg"},
	{gauntlet::SoundName::MAGIC_HEAL,               "mag_restoration_ff_fire_01.ogg"},
	{gauntlet::SoundName::MAGIC_SHOCK,              "mag_shout_ff_fire_01.ogg"},
	{gauntlet::SoundName::MAGIC_SPRINT,             "mag_shout_sprint_fire.ogg"},
	{gauntlet::SoundName::MAGIC_ABSORB,             "mag_wardtest_absorb.ogg"},
	{gauntlet::SoundName::MAGIC_GLASS_BREAK,        "mag_wardtest_break.ogg"},
	{gauntlet::SoundName::MAGIC_EFFECT_4,           "mag_wardtest_cast.ogg"}
};
