//
// Created by celeri on 5/31/16.
//

#ifndef GAUNTLET_CHARACTERMENUNAME_HH
#define GAUNTLET_CHARACTERMENUNAME_HH

namespace gauntlet
{
  enum CharacterMenuName :int
  {
    BERSERKER_MENU_SELECTION,
    VALKYRIE_MENU_SELECTION,
    MAGUS_MENU_SELECTION,
    RANGER_MENU_SELECTION
  };
}
#endif //GAUNTLET_CHARACTERMENUNAME_HH
