//
// Created by celeri on 5/26/16.
//

#ifndef GAUNTLET_SOUNDNAME_HH
#define GAUNTLET_SOUNDNAME_HH

namespace  gauntlet
{
  enum SoundName : int
    {
      SOUND_NONE = 0,
	MENU_SOUND,
	AMBIENT_DARKCORRIDORS,
	AMBIENT_UNDERLAND,
	AXE_HIT_SPROSH,
	AXE_HIT_SOFT,
	AXE_HIT_HARD,
	BATS_1,
	BATS_2,
	BATS_LOOP,
	BOW,
	BUTTON,
	COIN_BAG,
	COINS,
	DOOR_METAL_CLOSE,
	DOOR_METAL_OPEN,
	DOOR_WOOD_CLOSE,
	DOOR_WOOD_OPEN,
	DOOR_STONE,
	DOOR_GATE,
	EVENT_VICTORY,
	EVENT_DRAMATIC,
	EVENT_DISCOVERY,
	EVENT_DRUMS,
	EVENT_MYSTERY,
	HAMMER_HIT_HARD,
	HAMMER_HIT_SOFT,
	LEVER_LONG,
	LEVER_SHORT,
	MAP_CLOSE,
	MAP_OPEN,
	MUSIC_COMBAT_DRAMATIC,
	SPIKE_TRAP_1,
	SPIKE_TRAP_2,
	STEP_STONE_1,
	STEP_STONE_2,
	STEP_STONE_3,
	STEP_STONE_4,
	SWORD_HIT,
	SWORD_DRAW,
	FIRE_SMALL,
	FIRE_BIG,
	CORPSE,
	TREASURE_OPEN,
	TREASURE_CLOSE,
	RUBBISH,
	WATER_DROP
	};
};
#endif //GAUNTLET_SOUNDNAME_HH
